blank_issues_enabled: false
contact_links:
  # Replace the following URLs with your project's URLs
  - name: GitHub Discussions
    url: https://github.com/thombashi/github-issue-forms-template/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/thombashi/github-issue-forms-template
    about: Please check the documentation before creating an issue.
